name: "OpenVPN connector"
version: "0.0.0"
slug: folder
description: >-
  An addon that lets you connect your hass to your OpenVPN server with your .ovpn client file.
  If the connection goes down, ovpn already tries to reconnect automatically, unless specified otherwise in your config file.
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: https://github.com/MestreSales/hass-openvpn-client
host_network: true
privileged: ["NET_ADMIN"]
startup: "before"
init: false
schema: 
  filename: str